// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Day2.Models;

public partial class studentAudit
{
    public string ServerUserName { get; set; }

    public DateOnly? Date { get; set; }

    public string Note { get; set; }
}